platform :ios, '11.0'
use_frameworks!

target 'Summation-iOS-Client_Example' do
  pod 'Summation-iOS-Client', :path => '../'

  target 'Summation-iOS-Client_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
#    pod 'Sumation-iOS-Client', :path => '../'
  end
end
